### PR TITLE
Fixes #6

### LINKED ISSUE #6: error on startup
I've tested with and without "var:" in configuration.yaml.  With it enabled, this error is logged:

2019-08-30 19:30:17 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 223, in async_setup_platform
    self.hass, self.config, self.domain, platform_type
  File "/usr/src/homeassistant/homeassistant/setup.py", line 227, in async_prepare_setup_platform
    integration = await loader.async_get_integration(hass, platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 283, in async_get_integration
    Integration.resolve_from_root, hass, components, domain
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 154, in resolve_from_root
    manifest_path = pathlib.Path(base) / domain / "manifest.json"
  File "/usr/local/lib/python3.7/pathlib.py", line 908, in __truediv__
    return self._make_child((key,))
  File "/usr/local/lib/python3.7/pathlib.py", line 695, in _make_child
    drv, root, parts = self._parse_args(args)
  File "/usr/local/lib/python3.7/pathlib.py", line 649, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

### PR DESCRIPTION
**Pull request by ludeeus**

### CODE REVIEW

**Comment by snarky-snark** [comment]
Ah so simple, thanks!

**Comment by Swiftnesses** [comment]
Will this update be pushed via HACS?

**Comment by snarky-snark** [comment]
It is already available via HACS as part of the "develop" release. It will also be available in release v0.9.3.

**Comment by Swiftnesses** [comment]
@snarky-snark I realised that and made the switch, thanks 👍

**Pull request merged**
